<style>
	#SNB_Wrap_1702 {
		position: absolute;
		top: 0px;
		width: 220px;
		height: 100%;
		padding: 0;
		background: #e9e9ef;
		border-left: 1px solid #efefef;
		border-right: 1px solid #efefef; 
		border-bottom: 1px solid #efefef;
	}
	
	#SNB_Wrap_1702 h3 {
		text-shadow:1px 3px 3px #d9d9df;
	    padding: 28px 20px 12px 28px;
		height:40px;
		font-family: "Nanum Gothic Bold";
		font-size: 20px;
		color: #000;
		background-color: #e9e9ef;
		font-weight:900;
		border-top: 5px solid #17538e;
	}
	
	.snb_1702 {
		background: #fff;
	}
	
	.snb_1702 li.last {
		border-bottom: 5px solid #17538e;
	}
	
	/*
	.snb_1702 > li {
		border-bottom: 1px solid #d1d1d1;
	}
	*/
	.snb_1702 li a {
		display: block;
	}
	.snb_1702 li a.newdepth1.on {
		background: #17538e url(/Images/Common/ico_snbBtnUp.png) 195px 12px no-repeat;
		color: #fff;
	}
	.snb_1702 li a.newdepth1 {
		padding: 12px;
		background: url(/Images/Common/ico_snbBtnDown.png) 195px 12px no-repeat;
		font-family: "Nanum Gothic Bold";
		font-size: 15px;
		color: #222;
	}
	.snb_1702 li a.newdepth2.on{
		color: #007a3d;
		
	}
	.snb_1702 li a.newdepth2 {
		height:15px;
		padding: 8px 18px;
		font-family: "Nanum Gothic Bold";
		font-size: 13px;
		color: #333;
	}
	.snb_1702 li.long a {
		padding-right:4px;
	}
	.snb_1702 li .newdepth3_wrap.on {
		display:block;
	}
	.snb_1702 li .newdepth3_wrap {
		display:none;
		padding: 2px 8px;
		background: #efefef;
		font-family: "Nanum Gothic Bold";
		font-size: 13px;
		border-top:1px solid #cfcfcf;
		border-bottom:1px solid #cfcfcf;
	}
	.snb_1702 li a.newdepth3.on{
		color: #007a3d;
	}
	.snb_1702 li a.newdepth3 {
		height:15px;
		padding: 8px 1px 8px 18px;
		font-family: "Nanum Gothic Bold";
		font-size: 13px;
		color: #333;
	}

	.snb_1702 .newdepth2_wrap.on {
		display:block;
	}
	.snb_1702 .newdepth2_wrap {
		display:none;
		background: #f9f9f9;
		border-bottom:1px solid #cfcfcf;
	} /* background: #fffcef; */
	
	/* .newdepth2_wrap.no4 : 국비지원 무료과정 */
	.snb_1702 .newdepth2_wrap.no4 li:first-child a {
		height: 24px;
	}

	.snb_1702 .newdepth2_wrap.no4 li:not(:first-child) a {
		height: 30px;
	}
	
	.snb_1702 .newdepth2_wrap.no8 li:nth-child(2) a { height: 32px; }

	.snb_1702 .newdepth2_wrap.no9 li:not(:first-child) a {
		height: 34px;
	}
	
	.snb_1702 .newdepth2_wrap.no10 li:nth-child(1) a { height: 32px; }
	
	.snb_1702 .newwrap.up {
		background: #f7f7f7 url(/Images/Common/ico_snbBtnUp.png) 175px 7px no-repeat;
	}
	.snb_1702 .newwrap.down {
		background: url(/Images/Common/ico_snbBtnDown.png) 175px 6px no-repeat;
	}
	
	.snb_1702 .newdepth3_wrap.no2 {
		height: 314px;
	}
	.snb_1702 .newdepth3_wrap.no2 li:nth-child(3) a { height: 26px; }
	.snb_1702 .newdepth3_wrap.no2 li:nth-child(8) a { height: 26px; }
	.snb_1702 .newdepth3_wrap.no2 li:nth-child(9) a { height: 26px; }
	.snb_1702 .newdepth3_wrap.no3 {
		height: 130px;
	}
	.snb_1702 .newdepth3_wrap.no3 li a { height: 26px; }
	.snb_1702 .newdepth3_wrap.no5 {
		height: 212px;
	}
	.snb_1702 .newdepth3_wrap.no5 li:nth-child(1) a { height: 26px; }
	.snb_1702 .newdepth3_wrap.no6 li:nth-child(2) a { height: 26px; }
	.snb_1702 .newdepth3_wrap.no7 {
		height: 86px;
	}
	.snb_1702 .newdepth3_wrap.no7 li a { height: 25px; }
	
	
	
</style>
