<style>
	#SNB_Wrap_1709 {
		position: absolute;
		top: 0px;
		/*height: 100%;*/
		padding: 0;
		background: #e9e9ef;
		/*
		border-left: 1px solid #efefef;
		border-right: 1px solid #efefef; 
		border-bottom: 1px solid #efefef;
		*/
	}
	
	#SNB_Wrap_1709 h3 {
	     padding: 31px 8px;
		height:60px;		
		font-size: 23px;
		line-height:28px;
		color: #ffffff;
		background-color: #1b499b;
		margin-bottom:1px;
		font-weight:600;
		text-align:center;
	} /* textt-shadow:1px 3px 3px #d9d9df; font-family: "Nanum Gothic Bold"; */
	
	.snb_1709 {
		background: #fff;
	}
	
	/*
	.snb_1709 li.last {
		border-bottom: 5px solid #17538e;
	}
	*/
	
	/*
	.snb_1709 > li {
		border-bottom: 1px solid #d1d1d1;
	}
	*/
	.snb_1709 li a {
		display: block;
	}
	.snb_1709 li a.newdepth1.on {
		background-color:#44587b;
		color: #fff;
	} /* background: #17538e url(/Images/Common/ico_snbBtnUp.png) 195px 12px no-repeat; */
	.snb_1709 li a.newdepth1 {
		padding: 17px 10px;
		background: url(/Images/Common/ico_snbBtnDown.png) 195px 12px no-repeat;
		font-family: "Nanum Gothic Bold";
		font-size: 15px;
		color: #222;
		border-bottom:1px solid #a0a0a0;
	}
	.snb_1709 li a.newdepth2.on{
		color: #1b499b;
		
	}
	.snb_1709 li a.newdepth2 {
		height:22px;
		padding: 8px 18px;
		font-family: "Nanum Gothic Bold";
		font-size: 14px;
		color: #333;
	} /* height:15px; */
	.snb_1709 li.long a {
		padding-right:4px;
	}
	.snb_1709 li .newdepth3_wrap.on , .snb_1709 li .newdepth4_wrap.on {
		display:block;
	}
	.snb_1709 li .newdepth3_wrap , .snb_1709 li .newdepth4_wrap {
		display:none;
		margin: 2px 18px;
		background: #f8f8f8;
		font-family: "Nanum Gothic Bold";
		font-size: 14px;
		border:1px solid #cfcfcf;
	} /* padding: 2px 8px; */
	.snb_1709 li a.newdepth3.on , .snb_1709 li a.newdepth4.on {
		color: #1b499b;
	}  /* #007a3d */
	.snb_1709 li a.newdepth3 ,  .snb_1709 li a.newdepth4 {
		height:22px;
		padding: 8px 1px 8px 10px;
		font-family: "Nanum Gothic Bold";
		font-size: 14px;
		color: #333;
	} /* height:15px; */
	.snb_1709 li a.newdepth4 {
		padding: 8px 1px 8px 8px;
		font-size:13px;
		letter-spacing:-1px;
	}

	.snb_1709 .newdepth2_wrap.on {
		display:block;
	}
	.snb_1709 .newdepth2_wrap {
		display:none;
		background: #f8f8f8;
		border-bottom:1px solid #cfcfcf;
	} /* background: #fffcef; */
	
/*
	.snb_1709 .newdepth2_wrap.no4 li:first-child a {
		height: 24px;
	}

	.snb_1709 .newdepth2_wrap.no4 li:not(:first-child) a {
		height: 30px;
	}
	
	.snb_1709 .newdepth2_wrap.no8 li:nth-child(2) a { height: 32px; }

	.snb_1709 .newdepth2_wrap.no9 li:not(:first-child) a {
		height: 34px;
	}
	
	.snb_1709 .newdepth2_wrap.no10 li:nth-child(1) a { height: 32px; }
*/	
	.snb_1709 .newwrap.up {
		background: #f7f7f7 url(/Images/Common/ico_snbBtnUp.png) 175px 7px no-repeat;
	}
	.snb_1709 .newwrap.down {
		background: url(/Images/Common/ico_snbBtnDown.png) 175px 6px no-repeat;
	}
	.snb_1709 .newwrap.plus {
		background: #f7f7f7 url(/Images/Icons/icn_Plus.png) 130px 5px no-repeat;
	}
	.snb_1709 .newwrap.minus {
		background: url(/Images/Icons/icn_Minus.png) 130px 5px no-repeat;
	}
	
/*	
	.snb_1709 .newdepth3_wrap.no2 {
		height: 314px;
	}
	.snb_1709 .newdepth3_wrap.no2 li:nth-child(3) a { height: 26px; }
	.snb_1709 .newdepth3_wrap.no2 li:nth-child(8) a { height: 26px; }
	.snb_1709 .newdepth3_wrap.no2 li:nth-child(9) a { height: 26px; }
	.snb_1709 .newdepth3_wrap.no3 {
		height: 130px;
	}
	.snb_1709 .newdepth3_wrap.no3 li a { height: 26px; }
*/	
/*
	.snb_1709 .newdepth3_wrap.no5 {
		height: 212px;
	}
	.snb_1709 .newdepth3_wrap.no5 li:nth-child(1) a { height: 26px; }
	.snb_1709 .newdepth3_wrap.no6 li:nth-child(2) a { height: 26px; }
	.snb_1709 .newdepth3_wrap.no7 {
		height: 86px;
	}
	.snb_1709 .newdepth3_wrap.no7 li a { height: 25px; }
*/	
	
	
</style>
