<!-- con_wrap -->
<div class="con_wrap" style="z-index:1;">
	<h5>과정 로드맵</h5>
	<img src="img_Roadmap_893x382.png" usemap="Map1"/>
		<map name="Map1">
			<area shape="rect" coords="4,4,270,175" href="/Course/ShortCourse/DetailPage/Course_c.asp" >
			<area shape="rect" coords="304,4,567,175" href="http://www.bitacademy.com/Course/ShortCourse/DetailPage/Course_c2.asp" >
			<area shape="rect" coords="304,185,567,372" href="#" >
			<area shape="rect" coords="602,185,887,372" href="#" >
		</map>
</div>
<!-- //con_wrap -->

