<!-- con_wrap -->
<div class="con_wrap" style="z-index:1;">
	<h5>과정 로드맵</h5>
	<img src="img_Roadmap_1100.png" usemap="Map2" style="width:1100px;"/>
		<map name="Map2">
			<area shape="rect" coords="4,4,234,197" href="/Course/ShortCourse/DetailPage/Course_c.asp" >
			<area shape="rect" coords="282,4,498,197" href="/Course/ShortCourse/DetailPage/Course_c2.asp" >
			<area shape="rect" coords="547,4,800,197" href="/Course/ShortCourse/DetailPage/Course_AlgorithmIntermediate.asp" >
			<area shape="rect" coords="845,4,1095,197" href="/Course/ShortCourse/DetailPage/Course_AlgorithmAdvanced.asp" >
		</map>
</div>
<!-- //con_wrap -->

